site_name: "Chapa Sirithunge"
site_url: https://chapa-sirithunge.com
site_author: Chapa Sirithunge
site_description: "That's moi!"
copyright: Chapa Sirithunge
theme:
  #favicon: assets/images/logo.png
  #logo: assets/images/logo.png
  name: material
  #custom_dir: docs/overrides
  font:
    text: Noto Sans
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: lime
      accent: deep orange

nav:
  - Home: index.md
  - About Me: about_me.md
  - Projects:
    - Overview: projects/overview.md
    - Robopatient: projects/robopatient.md

plugins:
  - search
  
markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg